site_name: BulletTrade Docs
site_url: https://bullettrade.cn/docs/
repo_url: https://github.com/BulletTrade/bullet-trade
site_dir: ../bullettrade.cn/site/docs
docs_dir: docs
use_directory_urls: false
nav:
  - 官方首页: /
  - 文档首页: index.md
  - 回测引擎: backtest.md
  - 实盘引擎: live.md
  - 交易支撑: trade-support.md
  - 扩展能力: quickstart.md
  - API 文档: api.md
  - 数据源:
      - 数据源指南: data/DATA_PROVIDER_GUIDE.md
      - 聚宽数据: data/DATA_PROVIDER_JQDATA.md
      - MiniQMT 数据: data/DATA_PROVIDER_MINIQMT.md
      - Tushare 数据: data/DATA_PROVIDER_TUSHARE.md
  - 邀请贡献: contributing.md
  - QMT 服务配置: qmt-server.md
theme:
  name: material
  language: zh
  palette:
    - scheme: slate
      primary: aa
      accent: aa
  features:
    - navigation.tabs
    - navigation.tracking
    - search.suggest
    - toc.integrate
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
plugins:
  - search
  - mike:
      alias_type: redirect
      redirect_template: null
extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BulletTrade/bullet-trade
extra_css:
  - css/custom.css
